/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.apimanagement.deep;import cn.zhuatech.apimanagement.common.ApiResponse;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@RestController @RequestMapping("/api/apim") public class DeepDomainController{private final DeepDomainService s;/**
                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                  */
public DeepDomainController(DeepDomainService s){this.s=s;}/**
                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                             */
@GetMapping("/dashboard")ApiResponse<?> dashboard(@RequestParam String organizationCode){return ApiResponse.ok(s.dashboard(organizationCode));}/**
                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                            */
@PostMapping("/apis")ApiResponse<?> api(@Valid @RequestBody DeepDomainService.ApiRequest r){return ApiResponse.ok(s.register(r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
@PostMapping("/apis/{id}/submit")ApiResponse<?> submit(@PathVariable Long id){return ApiResponse.ok(s.submit(id));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
@PostMapping("/apps")ApiResponse<?> app(@Valid @RequestBody DeepDomainService.AppRequest r){return ApiResponse.ok(s.createApp(r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
@PostMapping("/subscriptions")ApiResponse<?> sub(@Valid @RequestBody DeepDomainService.SubscriptionRequest r){return ApiResponse.ok(s.subscribe(r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         */
@PostMapping("/apis/{id}/metrics")ApiResponse<?> metric(@PathVariable Long id,@Valid @RequestBody DeepDomainService.MetricRequest r){return ApiResponse.ok(s.recordMetric(id,r));}}
