/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.apimanagement.deep;
import cn.zhuatech.apimanagement.model.AuditLog;import cn.zhuatech.apimanagement.repository.AuditLogRepository;import jakarta.persistence.*;import jakarta.validation.constraints.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;import java.time.*;import java.util.*;
@Service @Transactional(readOnly=true) public class DeepDomainService{private final EntityManager em;private final AuditLogRepository audits;public DeepDomainService(EntityManager em,AuditLogRepository audits){this.em=em;this.audits=audits;}
 public ApiDashboard dashboard(String org){List<ApiView> apis=em.createQuery("select a from ManagedApi a where a.organizationCode=:o order by a.updatedAt desc",ManagedApi.class).setParameter("o",org).getResultList().stream().map(this::view).toList();List<AppView> apps=em.createQuery("select a from ConsumerApp a where a.organizationCode=:o order by a.createdAt desc",ConsumerApp.class).setParameter("o",org).getResultList().stream().map(a->new AppView(a.id,a.appCode,a.name,a.owner,a.clientFingerprint,a.status)).toList();List<SubscriptionView> subscriptions=em.createQuery("select s from ApiSubscription s where s.apiId in(select a.id from ManagedApi a where a.organizationCode=:o) order by s.createdAt desc",ApiSubscription.class).setParameter("o",org).getResultList().stream().map(this::view).toList();return new ApiDashboard(apis,apps,subscriptions,health(org));}
 @Transactional public ApiView register(ApiRequest r){if(r.basePath().contains(" ")||!r.basePath().startsWith("/"))throw bad("basePath必须以/开头且不能包含空格");if(existsApi(r.organizationCode(),r.apiCode(),r.apiVersion()))throw conflict("API编码与版本已存在");ManagedApi a=new ManagedApi(r.organizationCode(),r.apiCode(),r.apiVersion(),r.name(),r.basePath(),r.owner(),r.authType(),r.rateLimitPerMinute());em.persist(a);audit("API","登记API",r.apiCode(),r.apiVersion());return view(a);}
 @Transactional public ApiView submit(Long id){ManagedApi a=api(id);state(a,"DRAFT");if("NONE".equalsIgnoreCase(a.authType))throw conflict("企业API发布前必须配置认证方式");if(a.rateLimitPerMinute<=0)throw conflict("企业API发布前必须配置限流");a.status="IN_REVIEW";audit("API","提交发布",a.apiCode,a.apiVersion);return view(a);}
 @Transactional public ApiView publish(Long id){ManagedApi a=api(id);state(a,"IN_REVIEW");a.status="PUBLISHED";audit("API","批准上线",a.apiCode,a.basePath);return view(a);}
 @Transactional public AppView createApp(AppRequest r){String fingerprint=Integer.toHexString(Objects.hash(r.organizationCode(),r.appCode(),r.owner(),UUID.randomUUID())).repeat(8).substring(0,32);ConsumerApp a=new ConsumerApp(r.organizationCode(),r.appCode(),r.name(),r.owner(),fingerprint);em.persist(a);audit("APP","创建消费应用",r.appCode(),r.owner());return new AppView(a.id,a.appCode,a.name,a.owner,a.clientFingerprint,a.status);}
 @Transactional public SubscriptionView subscribe(SubscriptionRequest r){ManagedApi api=api(r.apiId());ConsumerApp app=app(r.appId());if(!api.organizationCode.equals(app.organizationCode))throw bad("API和消费应用必须属于同一组织");if(!"PUBLISHED".equals(api.status))throw conflict("只能订阅已发布API");ApiSubscription s=new ApiSubscription(api.id,app.id,r.environment(),r.dailyQuota());em.persist(s);audit("SUBSCRIPTION","申请订阅",api.apiCode,app.appCode+"/"+r.environment());return view(s);}
 @Transactional public SubscriptionView approve(Long id){ApiSubscription s=sub(id);if(!"PENDING".equals(s.status))throw conflict("只有待审批订阅可以批准");s.status="APPROVED";s.approvedAt=LocalDateTime.now();audit("SUBSCRIPTION","批准订阅",String.valueOf(id),s.environment);return view(s);}
 @Transactional public MetricView recordMetric(Long apiId,MetricRequest r){ManagedApi a=api(apiId);if(r.errors()>r.calls())throw bad("错误次数不能超过调用次数");ApiMetric m=new ApiMetric(apiId,r.windowStart(),r.calls(),r.errors(),r.p95LatencyMs());em.persist(m);audit("OBSERVABILITY","上报指标",a.apiCode,"success="+m.successRate);return new MetricView(m.id,apiId,m.windowStart,m.calls,m.errors,m.p95LatencyMs,m.successRate,healthOf(m));}
 public HealthSummary health(String org){List<ApiMetric> ms=em.createQuery("select m from ApiMetric m where m.apiId in(select a.id from ManagedApi a where a.organizationCode=:o) order by m.windowStart desc",ApiMetric.class).setParameter("o",org).setMaxResults(100).getResultList();long calls=ms.stream().mapToLong(m->m.calls).sum(),errors=ms.stream().mapToLong(m->m.errors).sum();double success=calls==0?100:Math.round((calls-errors)*10000d/calls)/100d;long degraded=ms.stream().filter(m->!"HEALTHY".equals(healthOf(m))).count();return new HealthSummary(calls,errors,success,degraded);}
 private String healthOf(ApiMetric m){return m.successRate>=99.9&&m.p95LatencyMs<=500?"HEALTHY":m.successRate>=98&&m.p95LatencyMs<=1500?"DEGRADED":"CRITICAL";}private ManagedApi api(Long id){ManagedApi a=em.find(ManagedApi.class,id);if(a==null)throw notFound("API不存在");return a;}private ConsumerApp app(Long id){ConsumerApp a=em.find(ConsumerApp.class,id);if(a==null)throw notFound("消费应用不存在");return a;}private ApiSubscription sub(Long id){ApiSubscription s=em.find(ApiSubscription.class,id);if(s==null)throw notFound("订阅不存在");return s;}private boolean existsApi(String o,String c,String v){return !em.createQuery("select a.id from ManagedApi a where a.organizationCode=:o and a.apiCode=:c and a.apiVersion=:v",Long.class).setParameter("o",o).setParameter("c",c).setParameter("v",v).getResultList().isEmpty();}private void state(ManagedApi a,String s){if(!s.equals(a.status))throw conflict("当前API状态不能执行该操作");}
 private ApiView view(ManagedApi a){return new ApiView(a.id,a.organizationCode,a.apiCode,a.apiVersion,a.name,a.basePath,a.owner,a.authType,a.rateLimitPerMinute,a.status,a.version);}private SubscriptionView view(ApiSubscription s){return new SubscriptionView(s.id,s.apiId,s.appId,s.environment,s.dailyQuota,s.status,s.version);}private void audit(String m,String a,String n,String d){audits.save(new AuditLog(m,a,n,"domain-service",d));}private ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}private ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}private ResponseStatusException notFound(String m){return new ResponseStatusException(HttpStatus.NOT_FOUND,m);}
 public record ApiRequest(@NotBlank String organizationCode,@NotBlank String apiCode,@NotBlank String apiVersion,@NotBlank String name,@NotBlank String basePath,@NotBlank String owner,@NotBlank String authType,@Positive int rateLimitPerMinute){}public record AppRequest(@NotBlank String organizationCode,@NotBlank String appCode,@NotBlank String name,@NotBlank String owner){}public record SubscriptionRequest(@NotNull Long apiId,@NotNull Long appId,@NotBlank String environment,@Positive long dailyQuota){}public record MetricRequest(@NotNull LocalDateTime windowStart,@PositiveOrZero long calls,@PositiveOrZero long errors,@PositiveOrZero int p95LatencyMs){}
 public record ApiView(Long id,String organizationCode,String apiCode,String apiVersion,String name,String basePath,String owner,String authType,int rateLimitPerMinute,String status,long version){}public record AppView(Long id,String appCode,String name,String owner,String clientFingerprint,String status){}public record SubscriptionView(Long id,Long apiId,Long appId,String environment,long dailyQuota,String status,long version){}public record MetricView(Long id,Long apiId,LocalDateTime windowStart,long calls,long errors,int p95LatencyMs,double successRate,String health){}public record HealthSummary(long calls,long errors,double successRate,long degradedWindows){}public record ApiDashboard(List<ApiView> apis,List<AppView> apps,List<SubscriptionView> subscriptions,HealthSummary health){}
}
