/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.apimanagement.deep;
import jakarta.persistence.*;import java.time.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="apim_apis",uniqueConstraints=@UniqueConstraint(columnNames={"organizationCode","apiCode","apiVersion"})) class ManagedApi{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Version long version;@Column(nullable=false,length=40)String organizationCode;@Column(nullable=false,length=50)String apiCode;@Column(nullable=false,length=20)String apiVersion;@Column(nullable=false,length=120)String name;@Column(nullable=false,length=120)String basePath;@Column(nullable=false,length=50)String owner;@Column(nullable=false,length=20)String authType;int rateLimitPerMinute;@Column(nullable=false,length=20)String status="DRAFT";LocalDateTime createdAt,updatedAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
protected ManagedApi(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
ManagedApi(String o,String c,String v,String n,String p,String owner,String auth,int rate){organizationCode=o;apiCode=c;apiVersion=v;name=n;basePath=p;this.owner=owner;authType=auth;rateLimitPerMinute=rate;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
@PrePersist void c(){createdAt=updatedAt=LocalDateTime.now();}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
@PreUpdate void u(){updatedAt=LocalDateTime.now();}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="apim_apps",uniqueConstraints=@UniqueConstraint(columnNames={"organizationCode","appCode"})) class ConsumerApp{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Column(nullable=false,length=40)String organizationCode;@Column(nullable=false,length=50)String appCode;@Column(nullable=false,length=120)String name;@Column(nullable=false,length=50)String owner;@Column(nullable=false,length=64)String clientFingerprint;@Column(nullable=false,length=20)String status="ACTIVE";LocalDateTime createdAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
protected ConsumerApp(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         */
ConsumerApp(String o,String c,String n,String owner,String fingerprint){organizationCode=o;appCode=c;name=n;this.owner=owner;clientFingerprint=fingerprint;createdAt=LocalDateTime.now();}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="apim_subscriptions",uniqueConstraints=@UniqueConstraint(columnNames={"apiId","appId","environment"})) class ApiSubscription{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Version long version;Long apiId;Long appId;@Column(nullable=false,length=20)String environment;long dailyQuota;@Column(nullable=false,length=20)String status="PENDING";LocalDateTime createdAt,approvedAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                           */
protected ApiSubscription(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
ApiSubscription(Long apiId,Long appId,String env,long quota){this.apiId=apiId;this.appId=appId;environment=env;dailyQuota=quota;createdAt=LocalDateTime.now();}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="apim_metrics",uniqueConstraints=@UniqueConstraint(columnNames={"apiId","windowStart"})) class ApiMetric{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;Long apiId;LocalDateTime windowStart;long calls;long errors;int p95LatencyMs;double successRate;/**
                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                           */
protected ApiMetric(){}/**
                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                  */
ApiMetric(Long apiId,LocalDateTime start,long calls,long errors,int p95){this.apiId=apiId;windowStart=start;this.calls=calls;this.errors=errors;p95LatencyMs=p95;successRate=calls==0?100:Math.round((calls-errors)*10000d/calls)/100d;}}
